[general]
working_directory = "Development"

[cursor]
style = "Block"

[font]
size = 16.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
opacity = 1.0
option_as_alt = "Both"

[window.padding]
x = 10
y = 10
